### ISSUE TITLE
always_inline could not be inlined.

### ISSUE THREAD

**Issue by matthiasbeyer** [larsendt/hashtable#5]
When I compile the library with `make`, it gives me the error message:

```
src/murmur.c:34:23: Warnung: always_inline könnte nicht als inline erzeugt werden [-Wattributes]
```

Translated (as good as I can):

```
src/murmur.c:34:23: Warning: always_inline could not be generated as inline [-Wattributes]
```

Any solution?

**Comment by larsendt** [comment]
Hi Matthias, 

Sorry for the delayed reply. I've been busy recently. 

The warning is coming from the murmur library, which I did not reply. The warning can be fixed by removing the FORCE_INLINE macro from lines 14, 19, 34 and 47 of murmur.c, however I'm not sure that's a good idea. In the case that the function cannot be inlined, it's not a problem for us, but if it can be inlined then we get a free performance boost. 

The other option would be to remove the -Wattributes warning (which is a part of -Wall, I believe). 

Cheers,
Dane

**Comment by larsendt** [comment]
Another possible fix can be found here: https://github.com/zfsonlinux/zfs/commit/10be533e3344f523e1b8d6ab4f0658897a95ac02

That seems like what we might want to do. If that looks good to you, I'll commit the changes.

Dane

**Comment by larsendt** [comment]
Or, even better, it looks like MurmurHash has been updated. I'll check the latest copy in. 

Dane
